import "./scripts/global";
import "./scripts/header";
import "./scripts/products-filtering";
import "./scripts/search-auto-complete";
import "./scripts/blocks/hero-block";
import "./scripts/blocks/categories-slider";
import "./scripts/single-product";
import "./scripts/brands-fetch";
import "./scripts/sliders";